# Generated by Django 4.0.4 on 2022-07-29 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='uploads/%Y/%m/%d/', verbose_name='Post image'),
            preserve_default=False,
        ),
    ]
