# Generated by Django 4.0.4 on 2022-07-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, max_length=200, upload_to='uploads/%Y/%m/%d/', verbose_name='Post image'),
        ),
    ]
