# Generated by Django 4.0.4 on 2022-07-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, default='post_images/default.jpg', max_length=200, null=True, upload_to='post_images/%y/%m/%d', verbose_name='Post Image'),
        ),
    ]
